CREATE DATABASE accentureManagment;

CREATE TABLE EMPRESA (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NOMEFANTASIA VARCHAR(150) NOT NULL,
	CNPJ VARCHAR(30) UNIQUE,
	CEP VARCHAR(10) NOT NULL
	
);

CREATE TABLE FORNECEDOR (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	CNPJ VARCHAR(30) UNIQUE,
	CPF VARCHAR(14) UNIQUE
);
